language: node_js
node_js:
  - "12"

addons:
  chrome: stable

before_script: 
  - npm install --prefix ./projects/lux

script:
  - npm install codecov -g
  - npm run test:travis
  - npm run build

after_success:
  - codecov -f coverage/lux/lcov.json

sudo: false