name: Pull Request Actions

on:
  pull_request:
    branches: [devel]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force
      - name: Lint lux
        run: npm run lint:lux
      - name: Lint app
        run: npm run lint
      - name: Test lux
        run: npm run test:coverage
      - name: Build lux
        run: npm run build:lux
      - name: Build app
        run: npm run build
