name: Pull Request Actions

on:
  pull_request:
    branches: [devel]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Clean install dependencies
        run: npm ci --force
      - name: Lint lux
        run: npm run lint:lux
      - name: Lint app
        run: npm run lint
      - name: Test lux
        run: npm run test:coverage
      - name: Build lux
        run: npm run build:lux
      - name: Build app
        run: npm run build
